[package]
name = "rustvideoplatform"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
mimalloc = { version = "*", features = ["secure"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "process", "io-util"] }
tokio-util = { version = "0.7", features = ["io"] }
axum = { version = "0.8", features = ["multipart", "json"] }
tower = "*"
tower-http = { version = "*", features = ["fs", "compression-br", "compression-zstd"] }
axum-server = { version = "0.8", features = ["tls-rustls"] }
axum-h3 = "*"
h3-util = { version = "0.0.5", features = ["quinn"] }
h3-quinn = "0.0.10"
quinn = "0.11"
rustls-pemfile = "2"
rustls = { version = "0.23", features = ["ring"] }
memory-serve = "1"
serde = { version = "1.0", features = ["derive"] }
scylla = "1.5"
askama = { version = "0.15", features = ["serde_json"] }
serde_json = "*"
minify-html-onepass = "0.18"
chrono = "0.4"
ahash = "*"
argon2 = "0.5"
rand = "0.10"
meilisearch-sdk = "0.32"
redis = { version = "1.0", features = ["tokio-comp", "connection-manager"] }
openssl = { version = "0.10", features = ["vendored"] }
totp-rs = { version = "5", features = ["qr", "otpauth"] }
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }
uuid = { version = "1", features = ["v4", "v5", "serde"] }
url = "2"
base32 = "0.4"
fluent-bundle = "0.15"
unic-langid = "0.9"
