services:
 rustapp:
   image: panmourovaty/rustvideoplatform
   ports:
    - "8080:8080"
   volumes:
     - ./source:/source
     - ./upload:/upload
     - ./config.json:/config.json
   restart: always
   depends_on:
     - scylladb
     - meilisearch
     - indexer
 source:
   image: nginx:alpine
   ports:
    - "8880:8880"
   volumes:
     - ./source:/source
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   restart: always
 processor:
   image: panmourovaty/rustvideoplatform-processor
   volumes:
     - ./upload:/upload
     - ./processor-config.json:/config.json
   restart: always
   devices:
     - /dev/dri/renderD128:/dev/dri/renderD128
   depends_on:
     - scylladb
     - whisper
     - translatellama
 indexer:
   image: panmourovaty/rustvideoplatform-indexer
   volumes:
     - ./source:/source
     - ./indexer-config.json:/config.json
   restart: always
   depends_on:
     - scylladb
     - meilisearch
     - dragonfly
 dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    volumes:
      - ./dragonfly:/data
 scylladb:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"
    volumes:
      - ./scylladb:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
    command: --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1
    restart: always
 meilisearch:
   image: getmeili/meilisearch:latest
   environment:
     - http_proxy
     - https_proxy
     - MEILI_MASTER_KEY=SECRET_PASSWORD
     - MEILI_NO_ANALYTICS=true
     - MEILI_ENV=production
     - MEILI_LOG_LEVEL
     - MEILI_DB_PATH=/data.ms
     - MEILI_EXPERIMENTAL_ALLOWED_IP_NETWORKS=any
 whisper:
   image: ghcr.io/ggml-org/whisper.cpp:main-vulkan
   container_name: whisper
   volumes:
     - ./models:/models
   entrypoint: ["whisper-server"]
   command: ["--host", "0.0.0.0", "--port", "8080", "-sns", "-fa", "-l" , "auto", "--vad","--vad-model", "/models/YOUR_VOICE_DETECTION_MODEL", "-m", "/models/YOUR_WHISPER_MODEL"]
   devices:
     - /dev/dri:/dev/dri
   stdin_open: true
   tty: true
 translatellama:
   image: ghcr.io/ggml-org/llama.cpp:server-vulkan
   container_name: translatellama
   volumes:
     - ./models:/models
   command: ["--host", "0.0.0.0", "--port", "8083", "-m", "/models/YOUR_TRANSLATION_MODEL", "--alias", "translation", "--no-webui"]
   ports:
     - "8083:8083"
   devices:
     - /dev/dri:/dev/dri
   stdin_open: true
   tty: true
 embedllama:
   image: ghcr.io/ggml-org/llama.cpp:server-vulkan
   container_name: embedllama
   volumes:
     - ./models:/models
   command: ["--host", "0.0.0.0", "--port", "8084", "-m", "/models/YOUR_QWEN3_EMBEDDING_MODEL", "--alias", "embedding", "--embedding", "--pooling", "cls", "--no-webui"]
   ports:
     - "8084:8084"
   devices:
     - /dev/dri:/dev/dri
   stdin_open: true
   tty: true
